import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

class EmployeeMatrixScreen extends StatelessWidget {
  const EmployeeMatrixScreen({super.key});

  buildPlutoRows() {
    List<PlutoRow> rows = [];
    for (var data in udata) {
      rows.add(PlutoRow.fromJson(data));
    }
    return rows;
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 22, horizontal: 12),
          child: Row(
            children: [
              LimitedBox(
                maxWidth: 130,
                child: Container(
                  color: Colors.amber.shade100,
                  child: const Text(" Atish"),
                ),
              ),
              const Spacer(),
              Expanded(
                flex: 4,
                child: SizedBox(
                  height: 30,
                  child: Row(
                    children: [
                      Flexible(
                        flex: 2,
                        child: TextFormField(
                          decoration: const InputDecoration(
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 0),
                          ),
                        ),
                      ),
                      const SizedBox(
                        width: 12,
                      ),
                      Flexible(
                        flex: 3,
                        child: DropdownButtonFormField(
                          decoration: const InputDecoration(
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 0),
                          ),
                          value: 0,
                          items: const [
                            DropdownMenuItem(
                              value: 0,
                              child: Text("Austin"),
                            ),
                            DropdownMenuItem(
                              value: 1,
                              child: Text("Texas"),
                            ),
                            DropdownMenuItem(
                              value: 2,
                              child: Text("Fort Worth"),
                            ),
                            DropdownMenuItem(
                              value: 3,
                              child: Text("Andy's Store"),
                            ),
                            DropdownMenuItem(
                              value: 4,
                              child: Text("Megan Palace"),
                            ),
                          ],
                          onChanged: (value) {},
                        ),
                      ),
                      const SizedBox(
                        width: 12,
                      ),
                      const CircleAvatar(
                        child: Text("Photo"),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Expanded(
          child: Padding(
            padding: const EdgeInsets.all(18.0),
            child: PlutoGrid(
              columns: [
                PlutoColumn(
                    field: 'contact',
                    type: PlutoColumnType.text(),
                    title: 'contact',
                    frozen: PlutoColumnFrozen.start,
                    enableEditingMode: false,
                    width: PlutoGridSettings.minColumnWidth),
                PlutoColumn(
                  field: 'name',
                  type: PlutoColumnType.text(),
                  title: 'name',
                  frozen: PlutoColumnFrozen.start,
                  enableEditingMode: false,
                ),
                PlutoColumn(
                  field: 'OSHA10',
                  type: PlutoColumnType.date(),
                  title: 'OSHA10',
                ),
                PlutoColumn(
                  field: 'OSHA200',
                  type: PlutoColumnType.date(),
                  readOnly: true,
                  title: 'OSHA30',
                ),
                PlutoColumn(
                  field: 'TrainingA',
                  type: PlutoColumnType.date(),
                  title: 'TrainingA',
                ),
                PlutoColumn(
                  field: 'TrainingB',
                  type: PlutoColumnType.date(),
                  title: 'TrainingB',
                ),
                PlutoColumn(
                  field: 'TrainingC',
                  type: PlutoColumnType.date(),
                  title: 'TrainingC',
                ),
                PlutoColumn(
                  field: 'TrainingD',
                  type: PlutoColumnType.date(),
                  title: 'TrainingD',
                ),
                PlutoColumn(
                  field: 'TrainingE',
                  type: PlutoColumnType.date(),
                  title: 'TrainingE',
                ),
                PlutoColumn(
                  field: 'TrainingF',
                  type: PlutoColumnType.date(),
                  title: 'TrainingF',
                ),
                PlutoColumn(
                  field: 'TrainingG',
                  type: PlutoColumnType.date(),
                  title: 'TrainingG',
                ),
                PlutoColumn(
                  field: 'TrainingH',
                  type: PlutoColumnType.date(),
                  title: 'TrainingH',
                ),
                PlutoColumn(
                  field: 'TrainingI',
                  type: PlutoColumnType.date(),
                  title: 'TrainingI',
                ),
                PlutoColumn(
                  field: 'TrainingJ',
                  type: PlutoColumnType.date(),
                  title: 'TrainingJ',
                ),
                PlutoColumn(
                  field: 'TrainingK',
                  type: PlutoColumnType.date(),
                  title: 'TrainingK',
                ),
              ],
              rows: buildPlutoRows(),
              columnGroups: const [],
              configuration: const PlutoGridConfiguration(
                columnSize: PlutoGridColumnSizeConfig(
                  autoSizeMode: PlutoAutoSizeMode.none,
                  resizeMode: PlutoResizeMode.normal,
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

List<Map<String, dynamic>> udata = [
  {
    "userID": "692",
    "OSHA200": "",
    "name": "Alberto Mendez Aleman",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "721",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "834",
    "OSHA200": "",
    "name": "Alejandro Mancilla",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "860",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "204",
    "OSHA200": "",
    "name": "Andres Flores",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "124",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "524",
    "OSHA200": "",
    "name": "Benjamin I Panjoj",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "551",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "198",
    "OSHA200": "",
    "name": "Candelario Castaneda",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "144",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "8",
    "OSHA200": "",
    "name": "Esteban Quintero",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "175",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "558",
    "OSHA200": "",
    "name": "Feliciano Jaimes Valencia",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "587",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "485",
    "OSHA200": "",
    "name": "Felipe Portillo",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "512",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "840",
    "OSHA200": "",
    "name": "Floriberto Loza SR",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "866",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "371",
    "OSHA200": "",
    "name": "Hugo Nunez Mendez",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "418",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "1076",
    "OSHA200": "",
    "name": "Ismael Davila",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "1082",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "886",
    "OSHA200": "",
    "name": "Israel Barrientos Calderon",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "907",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "486",
    "OSHA200": "",
    "name": "Jose Angel Uzarraga Valles",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "513",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "243",
    "OSHA200": "",
    "name": "Jose Luis Rodriguez (Foreman",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "250",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "796",
    "OSHA200": "",
    "name": "Jose Manuel Campos",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "823",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "1049",
    "OSHA200": "",
    "name": "Jose Rico",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "1061",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "622",
    "OSHA200": "",
    "name": "Jovanni Abarca",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "652",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "510",
    "OSHA200": "",
    "name": "Juan Martinez",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "537",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "598",
    "OSHA200": "",
    "name": "Mariano Jimenez",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "627",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "78",
    "OSHA200": "",
    "name": "Nicolas Dircio",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "301",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "509",
    "OSHA200": "",
    "name": "Pedro R Nunez",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "536",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "768",
    "OSHA200": "",
    "name": "Rafael Jaimes",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "795",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  },
  {
    "userID": "780",
    "OSHA200": "",
    "name": "Senovio Acuna",
    "OSHA10": "",
    "TrainingC": "",
    "TrainingA": "",
    "contact": "799",
    "TrainingB": "",
    "TrainingD": "",
    "TrainingE": "",
    "TrainingF": "",
    "TrainingG": "",
    "TrainingH": "",
    "TrainingI": "",
    "TrainingJ": "",
    "status": "active",
    "position": "Employee",
    "TrainingK": "",
  }
];
