import 'package:LSTime/table.dart';
import 'package:flutter/material.dart';

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  State<DashboardScreen> createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: EdgeInsets.symmetric(vertical: 22, horizontal: 12),
          child: Row(
            children: [
              LimitedBox(
                maxWidth: 130,
                child: Container(
                  color: Colors.amber.shade100,
                  child: Text("Hello Atish"),
                ),
              ),
              Spacer(),
              Expanded(
                flex: 4,
                child: SizedBox(
                  height: 30,
                  child: Row(
                    children: [
                      Flexible(
                        flex: 2,
                        child: TextFormField(
                          decoration: InputDecoration(
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 0),
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 12,
                      ),
                      Flexible(
                        flex: 3,
                        child: DropdownButtonFormField(
                          decoration: InputDecoration(
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 0),
                          ),
                          value: 0,
                          items: [
                            DropdownMenuItem(
                              value: 0,
                              child: Text("Austin"),
                            ),
                            DropdownMenuItem(
                              value: 1,
                              child: Text("Texas"),
                            ),
                            DropdownMenuItem(
                              value: 2,
                              child: Text("Fort Worth"),
                            ),
                            DropdownMenuItem(
                              value: 3,
                              child: Text("Andy's Store"),
                            ),
                            DropdownMenuItem(
                              value: 4,
                              child: Text("Megan Palace"),
                            ),
                          ],
                          onChanged: (value) {},
                        ),
                      ),
                      SizedBox(
                        width: 12,
                      ),
                      CircleAvatar(
                        child: Text("Photo"),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Expanded(
            child: UTable(
          cols: [
            UDataColumn(
              field: 'contact',
            ),
            UDataColumn(
              field: 'name',
            ),
            UDataColumn(
              field: 'OSHA10',
            ),
            UDataColumn(
              field: 'OSHA200',
            ),
            UDataColumn(
              field: 'TrainingA',
            ),
            UDataColumn(
              field: 'TrainingB',
            ),
            UDataColumn(
              field: 'TrainingC',
            ),
            UDataColumn(
              field: 'TrainingD',
            ),
            UDataColumn(
              field: 'TrainingE',
            ),
            UDataColumn(
              field: 'TrainingF',
            ),
            UDataColumn(
              field: 'TrainingG',
            ),
            UDataColumn(
              field: 'TrainingH',
            ),
            UDataColumn(
              field: 'TrainingI',
            ),
            UDataColumn(
              field: 'TrainingJ',
            ),
            UDataColumn(
              field: 'TrainingK',
            ),
          ],
          rowsFixed: [],
          rowsHeader: [],
          rowsFooter: [],
          rows: udata.map((e) => UDataRow(rowMap: e)).toList(),
          isResponsive: true,
          fixedColumns: 2,
        )),
      ],
    );
  }

  List<Map<String, dynamic>> fdata = [
    // {
    //   "ID": "Search",
    //   "Company": "ADK Sandwich Shop",
    //   "Location": "Universum Device RoomGeneral",
    //   "UID": "u_d76X3UGXXQFW",
    //   "UPOSName": "UPOS_REG1_A15Demo",
    //   "UPOSType": "AllURegister",
    //   "USerial": "UKEY9gvX65ZG2AjLzBbbNa",
    //   "UStatus": "AllActive",
    //   "Connection": "Remote Connect",
    //   "Action": "More Options Upgrade UPOS Upgrade Database Backup Database Console Details",
    // },
  ];

  List<Map<String, dynamic>> udata = [
    {
      "userID": "692",
      "OSHA200": "hello",
      "name": "Alberto Mendez Aleman",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "721",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "834",
      "OSHA200": "hello",
      "name": "Alejandro Mancilla",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "860",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "204",
      "OSHA200": "hello",
      "name": "Andres Flores",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "124",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "524",
      "OSHA200": "hello",
      "name": "Benjamin I Panjoj",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "551",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "198",
      "OSHA200": "hello",
      "name": "Candelario Castaneda",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "144",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "8",
      "OSHA200": "hello",
      "name": "Esteban Quintero",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "175",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "558",
      "OSHA200": "hello",
      "name": "Feliciano Jaimes Valencia",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "587",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "485",
      "OSHA200": "hello",
      "name": "Felipe Portillo",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "512",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "840",
      "OSHA200": "hello",
      "name": "Floriberto Loza SR",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "866",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "371",
      "OSHA200": "hello",
      "name": "Hugo Nunez Mendez",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "418",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "1076",
      "OSHA200": "hello",
      "name": "Ismael Davila",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "1082",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "886",
      "OSHA200": "hello",
      "name": "Israel Barrientos Calderon",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "907",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "486",
      "OSHA200": "hello",
      "name": "Jose Angel Uzarraga Valles",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "513",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "243",
      "OSHA200": "hello",
      "name": "Jose Luis Rodriguez (Foreman",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "250",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "796",
      "OSHA200": "hello",
      "name": "Jose Manuel Campos",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "823",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "1049",
      "OSHA200": "hello",
      "name": "Jose Rico",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "1061",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "622",
      "OSHA200": "hello",
      "name": "Jovanni Abarca",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "652",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "510",
      "OSHA200": "hello",
      "name": "Juan Martinez",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "537",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "598",
      "OSHA200": "hello",
      "name": "Mariano Jimenez",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "627",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "78",
      "OSHA200": "hello",
      "name": "Nicolas Dircio",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "301",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "509",
      "OSHA200": "hello",
      "name": "Pedro R Nunez",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "536",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "768",
      "OSHA200": "hello",
      "name": "Rafael Jaimes",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "795",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    },
    {
      "userID": "780",
      "OSHA200": "hello",
      "name": "Senovio Acuna",
      "OSHA10": "hello",
      "TrainingC": "hello",
      "TrainingA": "hello",
      "contact": "799",
      "TrainingB": "hello",
      "TrainingD": "hello",
      "TrainingE": "hello",
      "TrainingF": "hello",
      "TrainingG": "hello",
      "TrainingH": "hello",
      "TrainingI": "hello",
      "TrainingJ": "hello",
      "TrainingK": "hello",
    }
  ];
  List<Map<String, dynamic>> data = [
    {
      "ID": 0,
      "Company": "BOILCAT",
      "Location": "766 Ralph Avenue, Guthrie, Wyoming",
      "UID": "63c5a55bedda13cc929ecd71",
      "UPOSName": "Nita Walsh",
      "UPOSType": "POS",
      "USerial": "eaa3815d-f75d-49ad-9e1a-1b41540e7277",
      "UStatus": false,
      "Connection": "brown",
      "Action": "View"
    },
    {
      "ID": 1,
      "Company": "POOCHIES",
      "Location": "637 Hart Place, Mappsville, Northern Mariana Islands",
      "UID": "63c5a55be41dea64da68d220",
      "UPOSName": "Love Steele",
      "UPOSType": "Scanner",
      "USerial": "081e8889-51e3-46ca-b3a2-4d8ae45190b4",
      "UStatus": true,
      "Connection": "green",
      "Action": "Edit"
    },
    {
      "ID": 2,
      "Company": "CODACT",
      "Location": "431 Agate Court, Yettem, Michigan",
      "UID": "63c5a55b22001753b7613212",
      "UPOSName": "Hoover Guerrero",
      "UPOSType": "POS",
      "USerial": "49629bc2-4ffd-4de9-812d-095447560f22",
      "UStatus": false,
      "Connection": "brown",
      "Action": "Edit"
    },
    {
      "ID": 3,
      "Company": "SUREPLEX",
      "Location": "321 Hancock Street, Troy, Colorado",
      "UID": "63c5a55b92c90dc829294125",
      "UPOSName": "Laverne Hale",
      "UPOSType": "Scanner",
      "USerial": "e76c4148-d5eb-4d0d-8761-19d6d2826120",
      "UStatus": true,
      "Connection": "green",
      "Action": "Edit"
    },
    {
      "ID": 4,
      "Company": "STEELFAB",
      "Location": "761 Olive Street, Interlochen, Vermont",
      "UID": "63c5a55bbc8e1d298ed4f82b",
      "UPOSName": "Aisha Lewis",
      "UPOSType": "POS",
      "USerial": "dc76746b-6517-46f9-bf2a-c521912baa9f",
      "UStatus": true,
      "Connection": "green",
      "Action": "Edit"
    },
    {
      "ID": 5,
      "Company": "ZIALACTIC",
      "Location": "695 Denton Place, Leroy, Washington",
      "UID": "63c5a55bdc569f7646a6e6b4",
      "UPOSName": "Alisha Everett",
      "UPOSType": "Scanner",
      "USerial": "2c7c52e1-a0bb-4e90-9d85-824c6cd8b9d7",
      "UStatus": true,
      "Connection": "brown",
      "Action": "Edit"
    }
  ];
}

List<String> titles = ["ID", "Company", "Location", "UID", "UPOS Name", "UPOS Type", "USerial", "UStatus", "Connection", "Action"];
